# Generated by Django 3.1.7 on 2021-03-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210306_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
