# Generated by Django 3.1.7 on 2021-03-06 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210306_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.community'),
        ),
    ]
