# Generated by Django 3.1.7 on 2021-03-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210306_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='total_price',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='project',
            name='project_uri',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='achieved_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_supporters',
            field=models.IntegerField(null=True),
        ),
    ]
