# Generated by Django 3.1.7 on 2021-03-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210307_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
