# Generated by Django 3.1.6 on 2021-03-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210309_2313'),
        ('project', '0007_auto_20210309_2055'),
    ]

    operations = [
    ]
