# Generated by Django 3.1.7 on 2021-03-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('profile_image', models.URLField(max_length=2000, null=True)),
                ('card_number', models.CharField(max_length=16, null=True)),
                ('account_number', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('user_description', models.CharField(max_length=1000, null=True)),
                ('phone_number', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'verifications',
            },
        ),
    ]
