# Generated by Django 3.1.7 on 2021-03-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='updated_at',
        ),
    ]
