# Generated by Django 3.1.6 on 2021-03-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210309_1950'),
        ('user', '0003_auto_20210309_1954'),
    ]

    operations = [
    ]
